name: Build Eleventy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 08:00 UTC
  workflow_dispatch:       # Allows manual runs

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python deps
        run: |
          pip install boto3 requests

      - name: Sync logbooks
        run: |
          python write-data.py

      - name: Install JS deps & build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
